name: Test

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Initial tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: cargo test
